### PR TITLE
Cleanups and speed and memory improvements

### PR DESCRIPTION
**Pull request by jamsilva**
The title says it all, but you may not want to merge commit 4f55013, which improves memory use but is incompatible with previous savestates.

### CODE REVIEW

**Comment by meepingsnesroms** [comment]
Can you make it compatible with old save states?(you can't make the old version work with new save states but this version should be able to detect older versions and act accordingly)

**Comment by jamsilva** [comment]
I think so, but I may not have time to do it until the weekend. If I am able to do it earlier I will leave a comment here.

**Comment by Alcaro** [comment]
Deleting unused clutter, like that ZSNES ifdef, is fine. Deleting a SET macro while keeping the corresponding CLEAR macro will make people wonder why only one exists. Clarity is more important than avoiding unused stuff.

Speeding up code is fine in general, but unless it yields a noticable performance improvement, prefer clarity. No unwarranted square roots tricks or XOR swaps.

Compressing internal data is fine. Compressing externally-visible data while breaking compatibility (whether forward or backward), again, only if it gives a noticable benefit.

I'm not completely comfortable with this kind of fix-fifty-things-at-once PRs, either.

**Comment by twinaphex** [comment]
Thanks for the previous PR BTW. A user on PS Vita tells me this fixed some longstanding issues for him, so kudos for that.

**Comment by jamsilva** [comment]
@Alcaro
- I agree that clarity is very important. Regarding your specific example of the deleted macro, I also agree.
- While the xor swapping may have been a bit overboard, the replacement of a floating point conversion and operation to integer operations is important for soft-float platforms and removes the dependency on math.h for that specific file.
- Regarding the backwards compatibility I also agree and that is precisely the reason for my warning in this PR. I will review this and do it over to prevent issues.
- This PR actually does only 3 things: remove unused code, replace the distance calculation code for seta010.c and compression of data structures.
Thanks for the criticism though. I will redo the changes based on your feedback and create a different PR for each of the 3 things I mentioned as soon as I have some time.

@twinaphex 
That's great! I'm happy to hear that :)

**Comment by Alcaro** [comment]
I'm not completely convinced removing this sqrt matters (pretty sure that's not the only float around here, and that file is used only in F1 ROC II: Race of Champions which I'm pretty sure nobody cares about), but the base argument is valid.

I'll accept this compromise: Break out the mathemagics into a separate function implementing either sqrt(x) or sqrt(x*x+y*y) (your choice), and keep a comment or #ifdef containing the original implementation. I will test that both implementations return same value for everything. The mathematical operation sqrt(x*x+y*y) is called l²-norm or vector length.

I'm not very eager about either backwards- or forwards-compatibility changes to the savestates. It's a very big change, and anything backwards-compatible would be even bigger. Exactly how much does the retro_serialize_size return value change? On which platforms do we have problems with snes9x savestate size? Does performance regress on platforms where unaligned access is illegal and unaligned 4byte loads therefore need to be four 1byte reads, such as ARM?

I don't mind PRs doing three things if they're all small and uncontroversial, but for anything big and/or potentially controversial, better keep it separate.

**Comment by jamsilva** [comment]
This time I only removed unused code and fixes a couple of warning from clang.

**Comment by Alcaro** [comment]
This PR is closed, we can't merge it even if we'd want to.

I recommend creating a new one.

**Pull request closed without merging**
